version: '3'
services:
  csharp_app:
    container_name: csharp_app
    build:
      context: csharp-crud-api
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    networks:
      - friends-network
    depends_on:
      - db
    environment:
      ASPNETCORE_ENVIRONMENT: "Development"
      ConnectionStrings__DefaultConnection: "Host=db;Database=postgres;Username=postgres;Password=postgres"
  db:
    container_name: db
    image: postgres:12
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - "5432:5432"
    networks:
      - friends-network
    volumes:
      - pgdata:/var/lib/postgresql/data
  ui:
    container_name: ui
    build:
      context: frontend
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    networks:
      - friends-network
    depends_on:
      - csharp_app

volumes:
  pgdata: {}

networks:
  friends-network:
    driver: bridge
